#!/bin/bash

set -e -x

cd src-face
export FACE_HOME=`pwd`
echo "===== build.sh ====="
yum install -y opencv
rpm -ql opencv
rpm -ql python
export PYTHONPATH="/usr/bin/python2.7:$PYTHONPATH"
export PYTHONPATH="/usr/share/doc/opencv-2.4.5:$PYTHONPATH"
python opencv-face-camera.py

exit 0
