platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}
inputs:
- name: src-face

run:
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hey! Listen!"]

