platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

image_resource:
  type: docker-image
  source: {repository: python}

image_resource:
  type: docker-image
  source: {repository: binded/python-opencv}

inputs:
- name: src-face

run:
  path: ./src-face/build
