platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

  type: docker-image
  source: {repository: busybox}

inputs:
- name: src-face

outputs:
- name: app-face

run:
  path: gmq3@jpp4hifjkremkfgjmfperogifjqwepfrqfci3hmpoj
