#!/bin/bash

set -e -x

cd src-face
export FACE_HOME=`pwd`
echo "===== build.sh ====="
yum install -y opencv2
rpm -ql opencv2
export PYTHONPATH="/usr/local/lib/python2.7/site-packages/:$PYTHONPATH"
python opencv-face-camera.py

exit 0
